export const THEMES = [
    { name: "Light", code: "#edf2fa", value: "light"},
    { name: "Dark", code: "#282828", value: "dark"},
    { name: "Blue", code: "#1d2636", value: "blue"},
    { name: "Grey", code: "#1e2729", value: "grey"},
    { name: "Cool Grey", code: "#23262d", value: "cool_grey"},
    { name: "Aqua", code: "#102a27", value: "aqua"},
    { name: "Green", code: "#1c2918", value: "green"},
    { name: "Citron", code: "#2c250c", value: "citron"},
    { name: "Orange", code: "#362112", value: "orange"},
    { name: "Apricot", code: "#2f231c", value: "apricot"},
    { name: "Rose", code: "#371f24", value: "rose"},
    { name: "Fuchsia", code: "#32202f", value: "fuchsia"},
    { name: "Violet", code: "#292335", value: "violet"},
    { name: "Slate", code: "#182735", value: "slate"},
  ];